#!/bin/sh

# The system currently:
# * imports all enums as seeds
# * pulls in MASTER, ACFTREF
# * creates identifiers from MASTER
# * creates models from ACFTREF
# * creates aircrafts which associate identifiers to models
# 
# The batch runner doesn't like running after another batch runner. Likely it has
# to do with running connections being disconnected or something.

rake db:rebuild
rake aircraft:clear aircraft:source aircraft:identifiers --trace
rake aircraft:models --trace
rake aircraft:aircrafts --trace
