development:
  host: localhost
  database: aviation_data_development

staging:
  host: localhost
  database: aviation_data_development

production:
  host: localhost
  database: aviation_data_production

test:
  host: localhost
  database: aviation_data_test
