development:
  host: localhost
  database: avaition_data_development

staging:
  host: localhost
  database: avaition_data_development

production:
  host: localhost
  database: avaition_data_production

test:
  host: localhost
  database: avaition_data_test
