#!/usr/bin/env ruby
 
packages = FaaData::AircraftPackage.find

packages.each do |package|
  if package.import_date <= Aircraft.last_import_date
    puts "Skipping #{package.name}"
    next
  end

  puts
  puts "=========================="
  puts "Processing #{package.name}"
  puts "=========================="

  FaaData::Aircrafts.import_package(package)

  puts
  puts "Importing identifiers from MASTER"
  BatchImport::Identifiers.import_latest(package)

  puts
  puts "Importing models from ACFTREF"
  BatchImport::Models.import_latest(package)

  puts
  puts "Importing aircrafts from MASTER"
  BatchImport::Aircrafts.import_latest(package)
end
