#!/usr/bin/env ruby
 
FaaData::AircraftPackage.find.each do |package|
  puts
  puts "=========================="
  puts "Processing #{package.name}"
  puts "=========================="

  FaaData::Aircrafts.import_package(package)

  puts
  puts "Importing identifiers from MASTER"
  BatchImport::Identifiers.import_latest(package)

  puts
  puts "Importing models from ACFTREF"
  BatchImport::Models.import_latest

  puts
  puts "Importing aircrafts from MASTER"
  BatchImport::Aircrafts.import_latest(package)
end
