#!/usr/bin/env ruby

puts `rake db:rebuild`
 
FaaData::Package.find.each do |package|
  puts
  puts "=========================="
  puts "Processing #{package.name}"
  puts "=========================="

  FaaData.import_from_package(package)

  puts
  puts "Importing identifiers from MASTER"
  BatchImport::Identifiers.import_latest

  puts
  puts "Importing models from ACFTREF"
  BatchImport::Models.import_latest

  puts
  puts "Importing aircrafts from MASTER"
  BatchImport::Aircrafts.import_latest(package)
end
