#!/usr/bin/env ruby
 
FaaData::AirmenPackage.find.each do |package|
  if package.import_date <= Airman.last_import_date
    puts "Skipping #{package.name}"
    next
  end

  puts
  puts "=========================="
  puts "Processing #{package.name}"
  puts "=========================="

  FaaData::Airmen.import_package(package)

  puts
  puts "Importing airmen"
  BatchImport::Airmen.import_latest(package)

  puts
  puts "Importing certificates"
  BatchImport::Certificates.import_latest(package)
end
